import os
names=['Deep Convolutional Ranking for Multilabel Image Annotation','NUS-WIDE: A Real-World Web Image Database from National University of Singapore','Visual Attention Model for Name Tagging in Multimodal Social Media','Advances in deep learning approaches for image tagging','Content-Based Image Annotation Refinement','Measuring and Predicting Tag Importance for Image Retrieval','Multi-Label Cross-modal Retrieval','Instance Similarity Deep Hashing for Multi-Label Image Retrieval','Visual and semantic context modeling for scene-centric image annotation','TagProp: Discriminative Metric Learning in Nearest Neighbor Models for Image Auto-Annotation','Learning to Rank Image Tags With Limited Training Examples','Attend and Imagine: Multi-label Image Classification with Visual Attention and Recurrent Neural Networks','Multi-Modal Multi-Scale Deep Learning for Large-Scale Image Annotation','Multi-Label Image Classification via Knowledge Distillation from Weakly-Supervised Detection','Multi-label Triplet Embeddings for Image Annotation from User-Generated Tags','Semantic Regularisation for Recurrent Image Annotation','CNN-RNN: A Unified Framework for Multi-label Image Classification','Measuring and Predicting Tag Importance forImage Retrieval','Understanding and Predicting Importance in Images','Collecting Image Annotations Using Amazon’s Mechanical Turk','Image Tag Refinement TowardsLow-Rank, Content-Tag Prior and Error Sparsity','NMF-KNN: Image Annotation Using Weighted Multi-view Non-negative Matrix Factorization','Learning to Rank Image Tags with Limited Training Example','DenseCap: Fully Convolutional Localization Networks for Dense Captioning','CNN-RNN: A Unified Framework for Multi-label Image Classification','Multi-label Ranking from Positive and Unlabeled Data','Advances in deep learning approaches for image tagging']
links=['https://arxiv.org/pdf/1312.4894.pdf','https://lms.comp.nus.edu.sg/research/large-files/nuswide-civr2009.pdf','https://www.aclweb.org/anthology/P18-1185','https://www.microsoft.com/en-us/research/wp-content/uploads/2017/11/advances_in_deep_learning_approaches_for_image_tagging.pdf','http://sci-hub.tw/https://ieeexplore.ieee.org/abstract/document/4270246/','https://arxiv.org/pdf/1602.08680.pdf','https://web.iiit.ac.in/~viresh.ranjan/profile/publications/mlCCA.pdf','https://arxiv.org/pdf/1803.02987.pdf','https://www.researchgate.net/publication/300374349_Visual_and_semantic_context_modeling_for_scene-centric_image_annotation','http://class.inrialpes.fr/pub/guillaumin-iccv09b.pdf','https://www.researchgate.net/publication/271533178_Learning_to_Rank_Image_Tags_With_Limited_Training_Examples','http://sci-hub.tw/https://ieeexplore.ieee.org/document/8624407','https://arxiv.org/pdf/1709.01220.pdf','https://arxiv.org/pdf/1809.05884.pdf','http://sci-hub.tw/https://dl.acm.org/citation.cfm?id=3206061','https://arxiv.org/pdf/1611.05490.pdf','https://www.cv-foundation.org/openaccess/content_cvpr_2016/papers/Wang_CNN-RNN_A_Unified_CVPR_2016_paper.pdf','https://arxiv.org/pdf/1602.08680.pdf','https://sci-hub.tw/10.1109/cvpr.2012.6248100','https://www.aclweb.org/anthology/W10-0721','https://people.eecs.berkeley.edu/~yima/psfile/ACM-MM10.pdf','https://www.researchgate.net/publication/286594397_NMF-KNN_Image_Annotation_Using_Weighted_Multi-view_Non-negative_Matrix_Factorization#pf8','http://ijatir.org/uploads/216354IJATIR12004-499.pdf','https://arxiv.org/pdf/1511.07571.pdf','https://arxiv.org/pdf/1604.04573.pdf','https://zpascal.net/cvpr2016/Kanehira_Multi-Label_Ranking_From_CVPR_2016_paper.pdf','https://www.microsoft.com/en-us/research/wp-content/uploads/2017/11/advances_in_deep_learning_approaches_for_image_tagging.pdf'] 

failed_links=[]
idx=0
for name,link in zip(names,links):
    idx+=1
    if(len(link.split('.pdf'))==1):
        print ("Could not fetch for:","\nPaper:",name,"\nLink:",link)
        failed_links.append(link)
        #os.system(str("rm "+'_'.join(name.split(' '))+'.pdf'))
        continue
    print (idx," Downloading ...")
    print ("Paper :",name,"\nLink:",link)
    os.system(str("curl "+link+" > "+'_'.join(name.split(' '))+'.pdf'))
f = open('failed_links.txt','w')
f.write('\n'.join(failed_links))
